version: '3.3'
services:
  web:
    build: .
    ports:
     - "8000:80"
    depends_on:
     - redis
    container_name: deaddrop
    environment:
      - TZ=Europe/Paris
      - DEBIAN_FRONTEND=noninteractive
  redis:
    image: "redis:alpine"
    container_name: deaddropcache
    environment:
      - TZ=Europe/Paris
      - DEBIAN_FRONTEND=noninteractive
